# Generated by Django 3.2.9 on 2021-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
