# Generated by Django 3.2.9 on 2021-11-13 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_article_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='article',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
